FROM python:3.11-slim
WORKDIR /app
COPY . /app
ENV AI_ADMISSIBILITY_LOCAL_ONLY=1
ENV AI_ADMISSIBILITY_NO_EMAIL=1
ENV AI_ADMISSIBILITY_NO_OUTREACH=1
ENV AI_ADMISSIBILITY_NO_EXTERNAL_ACTION=1
CMD ["python", "demo/local_demo.py"]
